### ISSUE TITLE
Class tips

### ISSUE THREAD

**Issue by niclaslindstedt** [Classic-Fortress/server-qwprogs#244]
Give users tips on how to use their class

"Use the spanner (4) to upgrade, repair and stock your Sentry Gun"

etc

turn off with setinfo nct 1

**Comment by empezar** [comment]
Suggestions:

Scout:
"Use dash (e) to initiate a speed jump"
"To maintain the speed from dash (e), use strafe buttons and keep jumping"
"Drop caltrop canisters (mouse2) to slow the enemy down"
"Concussion grenades (f) temporarily disables anyone affected from moving rationally"
"The scout is a great flag capper thanks to his great speed"
"You can perform extreme jumps by throwing a concussion grenade (f) just before it explodes"
"The caltrop canister's (mouse2) slowing effect can be reversed by a medic or by picking up health"
"The concussion grenade (f) effect is active for up to 19 seconds"
"The Medic recovers from consussion grenade (f) effect twice as fast as other classes"
"The Scanner (5) will scan the area for players and flags"
"Use the Scanner menu (5) to choose which teams' players to scan for"
"The Scanner (5) can detect items and players through walls"
"The Scanner (5) consumes 2 cells every other second while active"

**Comment by drzel** [comment]
Soldier:
"Have a hand grenade ready to throw (mouse2) before entering combat. Timing is key."
"Use a nail grenade (f) to temporarily close off a bottle neck"
"Rocket jump off walls for a big bunny hopping boost."
"Jump as a hand grenade explodes in your hand to perform a grenade jump."
"Add a rocket jump to your grenade jump for even more distance and speed."
"Reload your current weapon (r) and secondary weapons (reloadnext) when you get the chance."
"With its faster rage of fire, and greater accuracy, the shotgun (3) is more useful over long distances."
"Swing your axe to show your team mates that you're not a spy."
"Use the shotgun to slow your enemy and the rocket launcher and grenades to finish them off."
"Kill the enemy demolitions expert to destroy his pipe trap."
"Use cover to take out a sentry gun with your rockets from distance."
"Jump on the spot when concussed to reduce it's throw effects."

**Comment by drzel** [comment]
Demolitions expert:

"Lay your pipe grenades (2) in a bottle neck and keep out of the way. Detonate them with (e)."
"Use your MIRV grenades (f) to close off a bottle neck while laying your pipes."
"On some maps, lay your detonation pack (5) near areas blocked by grates to open them."
"When your flag is out, cover it in pipe grenades. Detonate (e) before the enemy touches it."
"When your flag is going to get captured, reset your defence to stop chain captures."
"Your grenade launcher (1) and pipe launcher (2) share a clip. Reload (r) often."

**Comment by drzel** [comment]
Medic:

"Medic recovers from the effects of a concussion grenade (f) twice as fast as other classes."
"Use concussion grenades (f) to blast enemies away from you and to slow them down."
"Concussion grenade (f) blasts will penetrate walls. Use this to your advantage."
"The concussion grenade (f) blast effect is stronger toward the outside of its blast radius."
"Throw a concussion grenade on the ground, ...tbc

**Comment by drzel** [comment]
Pyro:

"Pyro's flamethrower doesn't work underwater."
"Use the flamethrower to burn your enemies, causing them to lose health over time."
"The flame thrower will blast back your enemies." tbc

**Comment by drzel** [comment]
Pyro:

"Pyro's flame thrower (1) doesn't work underwater."
"Use the flame thrower (1) to burn your enemies, causing them to lose health over time."
"The flame thrower (1) will blast back your enemies."
"Use napalm grenades (f) to block of a bottleneck.

**Comment by drzel** [comment]
Heavy Weapons Guy:

"The assault cannon takes  a while to spin up, use your class special (e) to keep in spinning."
"Avoid concussion grenades, they stop you from standing still, reducing your accuracy."
"Stand still to increase the accuracy of your assault cannon (1)."

**Comment by drzel** [comment]
Spy:

"The spy can disguise his team and class (5). Sneak past their defences."
"Knife (4) your enemy in the back for 3x damage."
"The spy can feign his death (e), dropping an empty backpack and printing a death message."
"Watch out for scouts, they will reveal your true identity if they touch you."
"The tranquilliser slows down your enemies."
"Using your weapon or picking up the flag will reveal your reveal your true identity."
"The spy can throw grenades without revealing his true identity."
"The gas grenade will annoy your enemies, causing them to hallucinate."

**Comment by drzel** [comment]
Engineer:

"The engineer can build sentry guns and ammo / armor dispensers (5)."
"Use the spanner (4) on your sentry guns to upgrade, repair, restock or rotate them."
"Use the spanner (4) on your team mates to repair their armor."
"Use the spanner (4) on your dispensers to add ammo and armor."
"Build your dispenser in a defensive position and detonate it (e) when an enemy is nearby."
"The more ammo in your dispenser, the more damage it does when it is detonated (e)."
"A sentry gun can be upgraded to level 3, giving it the ability to fire rockets."
"A sentry gun cannot be built on a moving platform."
"Watch out for spies. A sentry gun will not shoot a disguised enemy spy."
"The engineer's EMP grenade (f) will explode any nearby ammo including a demolition man's pipes."

**Comment by drzel** [comment]
Scout:
"The scout can perform a speed jump (e). This is great for initiating a bunny hop."
"Drop caltrops (mouse2) to slow the enemy down."
"Use concussion grenades (f) to blast enemies away from you and to slow them down."
"Concussion grenade (f) blasts will penetrate walls. Use this to your advantage."
"The concussion grenade (f) blast effect is stronger toward the outside of its blast radius."
"Throw a concussion grenade (f) then position yourself for the perfect concussion grenade jump."
"Concussion grenade (f) jumps can be chained for great distances."
"The scout is an excellent attacking class due to his speed and manoeuvrability."
"The scanner (5) can reveal the location of other players and the flag."

**Comment by drzel** [comment]
General:

"Have a grenade (mouse2 and f) ready to throw before entering combat. Timing is key."
"Reload your current weapon (r) and secondary weapons (reloadnext) whenever you get the chance."
"Swing your axe to show your team mates that you're not a spy."
"Kill the enemy demolitions expert to destroy his pipe trap."

**Comment by drzel** [comment]
Sniper:

"Throw flares (f) to illuminate a dark area."
"The sniper rifle (1) does more damage the longer you hold down fire (mouse1)."
"Use full auto mode (2) to pick off a weak enemy."
"Head shots deal double damage."
"Leg shots slow your enemy."
