### ISSUE TITLE
localinfo stockfull shouldn't work in enemy base

### ISSUE THREAD

**Issue by drzel** [Classic-Fortress/server-qwprogs#246]
On maps where there are packs available for the enemy (well6 / turtler / tf2k), stockfull shouldn't work.

Ie, well6, go soldier, gren up into enemy roof area above rr, destroy demoman because packs now give 100h 200a. normally these packs only gave 25h 25a or something like that.

I'm not sure if the packs include which team they belong to in entity information, but I believe they do.

**Comment by empezar** [comment]
Use map configs to disable stockfull for these maps
